# Generated by Django 5.1.2 on 2024-10-16 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_alumni_email_alumni_first_name_alumni_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_link', models.URLField(blank=True, max_length=255, null=True)),
                ('video_link', models.URLField(blank=True, max_length=255, null=True)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('alumni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='User.alumni')),
            ],
        ),
    ]
