# Generated by Django 5.1.2 on 2024-10-17 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='likes',
            field=models.ManyToManyField(related_name='liked_by', to='User.alumni'),
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(related_name='liked_posts', to='User.alumni'),
        ),
    ]
