# Generated by Django 5.1.2 on 2024-10-17 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_alumni_likes_remove_post_likes_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.AlterField(
            model_name='alumni',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_by', to='User.alumni'),
        ),
    ]
