# Generated by Django 5.1.2 on 2025-02-17 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_remove_alumni_user_alumni_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='password',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
