# Generated by Django 5.1.2 on 2025-02-18 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0013_alumni_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumni',
            name='user',
        ),
    ]
