# Generated by Django 5.1.2 on 2025-02-18 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0014_remove_alumni_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
