# Generated by Django 5.1.2 on 2025-02-18 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0015_alumni_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumni',
            name='is_active',
        ),
    ]
